name:         Apache-Test
version_from: lib/Apache/Test.pm
installdirs:  site

requires:
    Cwd:                           2.06
    File::Spec:                    0.8

distribution_type: module

no_index:
    package:
        - HTTP::Request::Common
        - warnings
    directory:
        - Apache-TestItSelf
